api_key: ''
songs:
  - Pauly Shore Lisa Lisa
  - Rick Astley Never Gonna Give You Up
  - Black Eyed Peas My Humps
  - Billy Rae Cyrus Achy Breaky Heart
  - Vanilla Ice Go Ninja Go
  - Aqua Barbie Girl
  - Snow Informer
  - Hanson Mmmbop
  - Los Del Rio Macarena
  - Baja Men Who Let The Dogs Out
  - Rebecca Black Friday
  - Spice Girls Wannabe
  - Milli Vanilli Blame It On The Rain
